### ISSUE TITLE
ament_cmake_core fails to build

### ISSUE THREAD

**Issue by m2-farzan** [m2-farzan/ros2-galactic-PKGBUILD#14]
Error:
```
==> Starting build()...
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.defaults': (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/colcon_core/entry_point.py", line 120, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/usr/lib/python3.10/site-packages/colcon_core/entry_point.py", line 168, in load_entry_point
    return entry_point.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))

...

==> ERROR: A failure occurred in build().
    Aborting...
Starting >>> ament_cmake_core
Starting >>> gtest_vendor
Aborted  <<< gtest_vendor [0.22s]

Summary: 0 packages finished [18.2s]
  1 package failed: ament_cmake_core
  1 package aborted: gtest_vendor
  1 package had stderr output: ament_cmake_core
  330 packages not processed
```

**Comment by m2-farzan** [comment]
Solution:
```
pip3 install colcon-core==0.7.0
```

This issue will be resolved as soon as [python-colcon-core](https://aur.archlinux.org/packages/python-colcon-core/) bumps to 0.7.0 or later.

Related: https://github.com/acxz/pkgbuilds/issues/161

**Comment by m2-farzan** [comment]
> This issue will be resolved as soon as [python-colcon-core](https://aur.archlinux.org/packages/python-colcon-core/) bumps to 0.7.0 or later.

Bumped to 0.7.1
